package hla.atm.commons.event;

public enum EventType {

	NO_CASH,
	TRANSACTION_STATUS,
	CLIENT_ENTERED,
	CLIENT_LEFT,
	QUEUE_SIZE_STATE_RESPONSE,
	LEAVE_REQUEST,
	ENTRY_REQUEST,
	WITHDRAWAL_REQUEST,
	CASH_REFILL_REQUEST,

}
